In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [5]:
arr1 = np.array([1,2,3])
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
#Veri oluşturma

In [6]:
arr2 = np.zeros(5)
print(arr2)

[0. 0. 0. 0. 0.]


In [7]:
arr2 = np.ones(5)
print(arr2)

[1. 1. 1. 1. 1.]


In [8]:
arr2 = np.ones((5,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr2 = np.full((2,4),3)
print(arr2)

[[3 3 3 3]
 [3 3 3 3]]


In [11]:
arr2 = np.arange(0,30,3)
print(arr2)

[ 0  3  6  9 12 15 18 21 24 27]


In [15]:
arr2 = np.linspace(0,100,20,dtype=int)
print(arr2)

[  0   5  10  15  21  26  31  36  42  47  52  57  63  68  73  78  84  89
  94 100]


In [17]:
arr2 = np.random.normal(25,4,(2,5))  #ortalama 25, standart sapma 4
print(arr2)

[[26.02601832 22.91100842 25.17562661 19.90299087 25.6895067 ]
 [14.89377035 19.04344742 23.35399359 28.47849251 25.18826775]]


In [19]:
arr2 = np.random.randint(5,10,(3,5))
print(arr2)

[[6 6 6 9 9]
 [9 5 9 8 6]
 [5 8 7 8 6]]


In [21]:
arr2.reshape(5,3)

array([[6, 6, 6],
       [9, 9, 9],
       [5, 9, 8],
       [6, 5, 8],
       [7, 8, 6]])