In [5]:
import numpy as np

In [12]:
arr = np.random.randint(1,10,10)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)


[9 2 3 7 3 7 1 7 2 9]
1
(10,)
10
int32


In [16]:
arr2 = np.linspace(1,20,10,dtype=int)
print(arr2)

[ 1  3  5  7  9 11 13 15 17 20]


In [19]:
concat = np.concatenate([arr,arr2])
print(concat)

[ 9  2  3  7  3  7  1  7  2  9  1  3  5  7  9 11 13 15 17 20]


In [22]:
a,b,c = np.split(concat,[3,9])
print(b)

[7 3 7 1 7 2]


In [36]:
np.sort(arr) #orjinal yapıyı bozmaz

array([1, 2, 2, 3, 3, 7, 7, 7, 9, 9])

In [31]:
print(arr)

[9 2 3 7 3 7 1 7 2 9]


In [35]:
arr.sort() #arrayın yapısını değiştirir
print(arr)

[1 2 2 3 3 7 7 7 9 9]


In [34]:
arr

array([1, 2, 2, 3, 3, 7, 7, 7, 9, 9])