In [3]:
import numpy as np
arr = np.array([1,3,5,7,8])
print(arr<3)
print(arr[arr>3])

[ True False False False False]
[5 7 8]


In [5]:
arr = np.arange(0,10)
print(arr.ndim)

1


In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.random.randint(10, size = (3,3,2))

array([[[6, 3],
        [8, 2],
        [5, 9]],

       [[3, 4],
        [2, 0],
        [1, 4]],

       [[0, 9],
        [0, 2],
        [3, 1]]])

In [11]:
arr = np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

arr[2][3]

8

In [12]:
v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])
v[-2]

9

In [14]:
v = np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])
[v[1],v[3]]

[3, 9]

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])