 #Seriler

In [30]:
import pandas as pd

import numpy as np

In [4]:
seri = pd.Series([1,3,4])

In [7]:
seri.axes

[RangeIndex(start=0, stop=3, step=1)]

In [8]:
seri.size

3

In [9]:
seri.values

array([1, 3, 4], dtype=int64)

In [13]:
pd.Series([1,4,6,7],index = [0,2,3,4])

0    1
2    4
3    6
4    7
dtype: int64

In [22]:
sozluk = pd.Series({"Istanbul":34,"Izmir":35,"Ankara":6,"Adana":1})
sozluk["Izmir":"Adana"]

Izmir     35
Ankara     6
Adana      1
dtype: int64

In [23]:
seri2 = pd.Series([1,5,9,4])
pd.concat([seri,seri2])

0    1
1    3
2    4
0    1
1    5
2    9
3    4
dtype: int64

#Dataframe

In [33]:
m = np.arange(1,10).reshape(3,3)

In [36]:
l = [1,5,8,43,3]
df = pd.DataFrame(m)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [37]:
df.axes

[RangeIndex(start=0, stop=3, step=1), RangeIndex(start=0, stop=3, step=1)]

In [38]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
df.head(1)

0  1  2
0  1  2  3

In [47]:
df.drop(1,inplace = True) #inplace = > kalıcı olarak değiştirir

KeyError: '[1] not found in axis'

In [48]:
df.drop(2,axis=1)

0  1
0  1  2
2  7  8

In [ ]:
#Loc ve Iloc

In [140]:
arr = np.random.randint(2017,2021,size=(10,2))
df1 = pd.DataFrame(arr,columns = ["Year1","Year2"])
df1

Year1  Year2
0   2019   2019
1   2020   2019
2   2019   2017
3   2018   2018
4   2020   2019
5   2017   2018
6   2018   2020
7   2018   2017
8   2020   2017
9   2018   2020

In [68]:
#loc

In [82]:
df1.loc[0:5,"Year1"]

0    2018
1    2018
2    2018
3    2017
4    2020
5    2018
Name: Year1, dtype: int32

In [84]:
df1.iloc[0:5,0:2]

Year1  Year2
0   2018   2019
1   2018   2018
2   2018   2018
3   2017   2017
4   2020   2020

In [91]:
df1[["Year1","Year2"]][0:2]

Year1  Year2
0   2018   2019
1   2018   2018

In [100]:
df1[df1.Year1>2018][["Year2","Year1"]]

Year2  Year1
4   2020   2020
8   2017   2019
9   2017   2019

In [141]:
df2 = df1-12
df2

Year1  Year2
0   2007   2007
1   2008   2007
2   2007   2005
3   2006   2006
4   2008   2007
5   2005   2006
6   2006   2008
7   2006   2005
8   2008   2005
9   2006   2008

In [145]:
df3 = pd.concat([df1,df2],ignore_index=True)
df3.values

array([[2019, 2019],
       [2020, 2019],
       [2019, 2017],
       [2018, 2018],
       [2020, 2019],
       [2017, 2018],
       [2018, 2020],
       [2018, 2017],
       [2020, 2017],
       [2018, 2020],
       [2007, 2007],
       [2008, 2007],
       [2007, 2005],
       [2006, 2006],
       [2008, 2007],
       [2005, 2006],
       [2006, 2008],
       [2006, 2005],
       [2008, 2005],
       [2006, 2008]])

In [105]:
?pd.concat

Signature:
pd.concat(
    objs,
    axis=0,
    join='outer',
    join_axes=None,
    ignore_index=False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity=False,
    sort=None,
    copy=True,
)
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a dict is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along.
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes on othe

In [113]:
df3.columns = ("year1","year2")
df3.columns

Index(['year1', 'year2'], dtype='object')

In [124]:
df4 = pd.DataFrame([2006],columns = ["year1"])
df4

year1
0   2006

In [123]:
pd.concat([df3,df4],join = "inner",ignore_index=True)

year1
0    2018
1    2018
2    2018
3    2017
4    2020
5    2018
6    2017
7    2017
8    2019
9    2019
10   2006
11   2006
12   2006
13   2005
14   2008
15   2006
16   2005
17   2005
18   2007
19   2007
20   2004
21   2006

In [126]:
pd.concat([df3,df4],join_axes = [df3.columns] ,ignore_index=True)

C:\Users\ardaa_iyfsapc\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  """Entry point for launching an IPython kernel.


year1   year2
0    2018  2019.0
1    2018  2018.0
2    2018  2018.0
3    2017  2017.0
4    2020  2020.0
5    2018  2017.0
6    2017  2020.0
7    2017  2019.0
8    2019  2017.0
9    2019  2017.0
10   2006  2007.0
11   2006  2006.0
12   2006  2006.0
13   2005  2005.0
14   2008  2008.0
15   2006  2005.0
16   2005  2008.0
17   2005  2007.0
18   2007  2005.0
19   2007  2005.0
20   2006     NaN

In [151]:
df1 = pd.DataFrame({"İsim": ["Arda","Mert","Tuna"],"Yıl":[2018,2020,2010]})
df2 = pd.DataFrame({"İsim": ["Arda","Mert","Tuna"],"Maaş":[4018,3020,10010]})
pd.merge(df1,df2)
numbers = pd.Series()
numbers.dtype

dtype('float64')