# Değişken Standardizasyonu

In [1]:
import numpy as np
import pandas as pd

In [3]:
V1 = np.array([1,3,5,7,9])
V2 = np.array([6,6,9,3,7])
V3 = np.array([3,6,7,8,6])
df = pd.DataFrame({
    "V1":V1,
    "V2":V2,
    "V3":V3
})
df = df.astype(float)
df

V1   V2   V3
0  1.0  6.0  3.0
1  3.0  6.0  6.0
2  5.0  9.0  7.0
3  7.0  3.0  8.0
4  9.0  7.0  6.0

# Standardizasyon

In [4]:
from sklearn import preprocessing

In [5]:
preprocessing.scale(df)

array([[-1.41421356, -0.10314212, -1.79284291],
       [-0.70710678, -0.10314212,  0.        ],
       [ 0.        ,  1.44398974,  0.5976143 ],
       [ 0.70710678, -1.65027399,  1.19522861],
       [ 1.41421356,  0.4125685 ,  0.        ]])

# Normalizasyon

In [6]:
preprocessing.normalize(df)

array([[0.14744196, 0.88465174, 0.44232587],
       [0.33333333, 0.66666667, 0.66666667],
       [0.40160966, 0.7228974 , 0.56225353],
       [0.63375022, 0.27160724, 0.72428597],
       [0.69853547, 0.54330537, 0.46569032]])

# Min-Max Dönüşümü

In [9]:
scaler = preprocessing.MinMaxScaler(feature_range = (0,100))
scaler.fit_transform(df)

array([[  0.        ,  50.        ,   0.        ],
       [ 25.        ,  50.        ,  60.        ],
       [ 50.        , 100.        ,  80.        ],
       [ 75.        ,   0.        , 100.        ],
       [100.        ,  66.66666667,  60.        ]])

# Değişken Dönüşümleri

In [11]:
import seaborn as sns

In [13]:
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 0-1 Dönüşümü

In [14]:
from sklearn.preprocessing import LabelEncoder

In [18]:
lbe = LabelEncoder()
lbe.fit_transform(df["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [20]:
df["new_sex"] = lbe.fit_transform(df["sex"])
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

## 1 Ve Diğerleri(0)

In [25]:
import numpy as np
df["new_day"] = np.where(df["day"].str.contains("Sun"),1,0)
df

total_bill   tip     sex smoker   day    time  size  new_sex  new_day
0         16.99  1.01  Female     No   Sun  Dinner     2        0        1
1         10.34  1.66    Male     No   Sun  Dinner     3        1        1
2         21.01  3.50    Male     No   Sun  Dinner     3        1        1
3         23.68  3.31    Male     No   Sun  Dinner     2        1        1
4         24.59  3.61  Female     No   Sun  Dinner     4        0        1
..          ...   ...     ...    ...   ...     ...   ...      ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3        1        0
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0        0
241       22.67  2.00    Male    Yes   Sat  Dinner     2        1        0
242       17.82  1.75    Male     No   Sat  Dinner     2        1        0
243       18.78  3.00  Female     No  Thur  Dinner     2        0        0

[244 rows x 9 columns]

## Çok Sınıflı Dönüşüm

In [26]:
lbe = LabelEncoder()

In [28]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

## One Hot 

In [30]:
df_one_hot = pd.get_dummies(df,columns = ["sex"], prefix = ["sex"])

In [37]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  new_sex  new_day  sex_Male  \
0       16.99  1.01     No  Sun  Dinner     2        0        1         0   
1       10.34  1.66     No  Sun  Dinner     3        1        1         1   
2       21.01  3.50     No  Sun  Dinner     3        1        1         1   
3       23.68  3.31     No  Sun  Dinner     2        1        1         1   
4       24.59  3.61     No  Sun  Dinner     4        0        1         0   

   sex_Female  
0           1  
1           0  
2           0  
3           0  
4           1